# 项目相关配置
myblog:
  # 名称
  name: Guo Huaijian
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/myblog/uploadPath，Linux配置 /home/myblog/uploadPath）
  profile: D:/myblog/uploadPath
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path:
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# Spring配置
spring:
  profiles:
    # 激活application-druid配置
    active: druid
      # redis 配置
  redis:
        # 地址
        host: 192.168.251.218
        # 端口，默认为6379
        port: 6379
        # 连接超时时间
        timeout: 10s
        password: egame218_@
        lettuce:
          pool:
            # 连接池中的最小空闲连接
            min-idle: 0
            # 连接池中的最大空闲连接
            max-idle: 8
            # 连接池的最大数据库连接数
            max-active: 8
            # #连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: -1ms

# 七牛云配置
qiniuyun:
  accessKey: uTOvafM0JSPSgZxYIVsxLf1QEnraVeC2PfpAtkRx
  secretKey: b9LgbcHKqEdhtwYmHn9Af5i2iewXWiNf_XR0J3n_
  #创建的存储空间名
  bucket: autumnleaves
  #对应存储空间的访问域名
  path: http://image.guohuaijian.com
  imageMaxSize: 52428800
  imageMaxNameLength: 200

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  # 搜索指定包别名
  typeAliasesPackage: com.pzhu.myblog.project.**.domain
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#oauth2配置
oauth2:
  grant_type: password
  client_id: client
  client_secret: secret

# 日志配置
logging:
  level:
    com.pzhu.myblog: debug
    org.springframework: warn
